### PR TITLE
Add ostree admin set-default

### PR DESCRIPTION
**Pull request by ghost**
Adds https://github.com/Szwendacz99/fedora-immutable-cheatsheet/issues/1

### CODE REVIEW

**Comment by Szwendacz99** [comment]
This command would certainly be usefull, but I think the placement could be improved. From what I tested it also potentially "vanishes" latest deployment if it is not booted yet and you set index to non-zero. Try for example layering package, and then setting default index to 1 before rebooting into that deployment. The deployment with additional package will be gone. I think the best would be to add additional section in "Emergency fallback", before "falling back to any previous commit of the system branch". The new section could be titled something like "booting previous deployment".  In such section showing grup with "shift" could be mentioned, choosing deployment with the "ostree admin set-default", but also deployment pinning.
What do you think?

**Comment by ghost** [comment]
In that case, if a new "booting previous deployment" section is added, `rpm-ostree rollback` should also be included alongside the set-default command.

**Comment by ghost** [comment]
Deployment pinning is not related to "booting previous deployment"
I personally think it should stay in the "emergency fallback section"

**Comment by Szwendacz99** [comment]
OK, thanks!

**Pull request merged**
